version: "3.9"

services:
  backend:
    build: ./backend  # dùng Dockerfile 
    container_name: node_backend
    ports:
      - "4000:4000"


  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

