version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "4000:4000"
